version: 0.2
env:
  parameter-store:
   KATALON_API_KEY: /CodeBuild/KATALON_API_KEY
phases:
  pre_build:
    commands:
      - docker pull katalonstudio/katalon:9.3.2
  build:
    commands:
      - docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon:9.3.2 katalon-execute.sh -apiKey=$API_KEY -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/New Test Suite"
artifacts:
  files:
    - report/*
reports: #New
  KatalonTestReports: # CodeBuild will create a report group called "KatalonTetReport".
    files: #Store all of the files
      - 'report/JUnit_Report.xml'

